### ISSUE TITLE
ecdsa ethereum compatible

### ISSUE THREAD

**Issue by elichai** [ethereumproject/libsecp256k1-rs#6]
Hi,
Does the signing function compatible with ethereum? it looks like it uses sha256 instead of keccak256:
https://github.com/ETCDEVTeam/libsecp256k1-rs/blob/master/src/lib.rs#L302

Is it possible to get the hashing mechanism out of the signing or replace sha256 with keccak256?

Thanks,
Elichai.

**Comment by sorpaas** [comment]
Just writing down the answer from gitter, in case anyone else's looking for it. :)

Yes, it is ethereum-compatible. HMAC-SHA256 is used in that line for nonce generation, as defined in RFC 6979.
